### ISSUE TITLE
createStudy2GDS1KG, Error in addStudyGDSSample(gdsSample, pedDF = pedStudy, batch = batch,  :    List of samples includes samples not present in the 'pedDF' data frame. The sample names must be present in the 'Name.ID' column.

### ISSUE THREAD

**Issue by mdozmorov** [KrasnitzLab/RAIDS#171]
I'm following the tutorial at https://krasnitzlab.github.io/RAIDS/articles/aicsPaper.html. Downloaded the 1KG GDS file, created snp-pileup files, and stuck at the sub-step 4 of step 2. The function:
```r
    createStudy2GDS1KG(PATHGENO = PATHGENO,
                   pedStudy = pedDF,
                   fileNameGDS = file.GDS,
                   listSamples = listSamp,
                   studyDF = studyDF,
                   PATHSAMPLEGDS = PATHSAMPLEGDS)
```
processes the first sample (creates the GSD file) and breaks with 
```
Error in addStudyGDSSample(gdsSample, pedDF = pedStudy, batch = batch,  : 
  List of samples includes samples not present in the 'pedDF' data frame. The sample names must be present in the 'Name.ID' column.
```
It also breaks with the same error if I specify any other sample, like:
```r
> pedDF[3, , drop = FALSE]
  Name.ID   Case.ID   Sample.Type Diagnosis Source
3   BCM03 Patient_3 Primary Tumor    Cancer    BCM
> listSamples[3]
[1] "BCM03"

    createStudy2GDS1KG(PATHGENO = PATHGENO,
                   pedStudy = pedDF[3, , drop = FALSE],
                   fileNameGDS = file.GDS,
                   listSamples = listSamples[3],
                   studyDF = studyDF,
                   PATHSAMPLEGDS = PATHSAMPLEGDS)
```
What may be wrong?

**Comment by mdozmorov** [comment]
Rerunning the function after the error results in another error
```
Error in openfn.gds(filename, readonly, allow.duplicate = allow.duplicate,  : 
  The file 'Ancestry/RAIDS/matGeno1000g.gds' has been created or opened.
```
It can be resolved by restarting the R session but creates delays.

**Comment by adeschen** [comment]
Hi Mikhail, 

Can you try assigning the Name.ID in the pedDF as the rownames of the data.frame:
> rownames(pedDF) <- pedDF$Name.ID

That step seems to be missing from the documentation. 

Let us know if that solve the problem.

Best,
Astrid

**Comment by belleau** [comment]
The second error is problably because the GDS file is open (maybe without a link).
You can close all GDS file with:

show file.gds(closeall=TRUE, verbose=TRUE)

Best,

Pascal

**Comment by belleau** [comment]
Just a correction the
showfile.gds(closeall=FALSE, verbose=TRUE)
don't have space between show and file (probably orthograph correction)
Best,

Pascal

**Comment by mdozmorov** [comment]
Yes, that solves it. Both suggestions, `rownames(pedDF) <- pedDF$Name.ID` and `showfile.gds(closeall=FALSE, verbose=TRUE)`, would be great to add to the documentation. Also, there's two extra parentheses in the function's call, `createStudy2GDS1KG(... PATHSAMPLEGDS = PATHSAMPLEGDS)**))**`. I can make a PR, but those are simple fixes. Thanks, Astrid, Pascal!
Mikhail

**Comment by adeschen** [comment]
I have updated the vignette and changed the error message to mention the row names requirement.

**Comment by mdozmorov** [comment]
The following step, [Sub-Step 5](https://krasnitzlab.github.io/RAIDS/articles/aicsPaper.html#sub-step-5--generate-a-pruned-subset-of-the-single-nucleotide-variants-snvs), throws another error. Can open a separate issue if it is.

The for loop runs three functions, `pruningSample`, `add1KG2SampleGDS`, `addStudy1Kg`. I put `print` statements before each to monitor sample and function progress. The first sample processes correctly. The second - `add1KG2SampleGDS` breaks.

```r
[1] "pruningSample 1"
[1] "add1KG2SampleGDS 1"
[1] "addStudy1Kg 1"
study.annot DONE 2022-10-24 20:02:33
[1] "pruningSample 2"
[1] "add1KG2SampleGDS 2"
Error in read.gdsn(index.gdsn(gdsSample, "geno.ref"), start = c(1, posCur),  : 
  The length of 'start' is invalid.
```
What may be wrong?

**Comment by adeschen** [comment]
Hi Mikhail,

I have opened an new issue  https://github.com/KrasnitzLab/RAIDS/issues/174
