### ISSUE TITLE
Problem in Sub-Step 5 of step 2

### ISSUE THREAD

**Issue by adeschen** [KrasnitzLab/RAIDS#174]
The  [Sub-Step 5](https://krasnitzlab.github.io/RAIDS/articles/aicsPaper.html#sub-step-5--generate-a-pruned-subset-of-the-single-nucleotide-variants-snvs) of Step 2, throws an error. 

The for loop runs three functions, pruningSample, add1KG2SampleGDS, addStudy1Kg. 

The print statements before each to monitor sample and function progress follows. The first sample processes correctly. The second - add1KG2SampleGDS breaks.

[1] "pruningSample 1"
[1] "add1KG2SampleGDS 1"
[1] "addStudy1Kg 1"
study.annot DONE 2022-10-24 20:02:33
[1] "pruningSample 2"
[1] "add1KG2SampleGDS 2"
Error in read.gdsn(index.gdsn(gdsSample, "geno.ref"), start = c(1, posCur),  : 
  The length of 'start' is invalid.

**Comment by adeschen** [comment]
I can see that there is a problem in the documentation:

    ## Add the genotype information for the list of pruned SNVs 
    ## into the GDS Sample file
    ## The genotype information is extracted from the 1KG GDS file
    add1KG2SampleGDS(gds = gds_1KG, gdsSampleFile = file.GDSSample, 
                        sampleCurrent = listSamples[1], 
                        study.id = studyDF$study.id))


> sampleCurrent = listSamples[1] 
should be  
> sampleCurrent = listSamples[i]

**Comment by mdozmorov** [comment]
That was a simple fix. My eyesight is not that sharp to catch it immediately. So yes, fixing `listSamples[i]` solved the problem. After correcting the documentation, this issue can be closed. Thanks, Astrid!

**Comment by adeschen** [comment]
The documentation has been updated.
